services:
  accounts:
    image: "beloved239/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - beloved
  loans:
    image: "beloved239/loans:s4"
    container_name: loans-ms
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - beloved
  cards:
    image: "beloved239/cards:s4"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - beloved
networks:
  eazybank:
    driver: "bridge"